### ISSUE TITLE
[BUG] - PC XPLANE UDP LIVERY Blank

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#351] opened 2023-10-05 20:56 UTC
### Describe the bug

Still getting pilots who are coming through with no livery listed. It'll pick up the aircraft but doesn't include the livery folder name
They're PC running the SC3 in "xplane" tracker mode.

```
[19:30:47] Using X-Plane
[19:30:47] Flying Cirrus Vision SF50
[19:30:47] Engine 1 On
[19:30:47] Now boarding
```

```
[22:07:14] Using X-Plane
[22:07:14] Flying ToLiss Airbus A340-642 HiDef
[22:07:14] Now boarding
```

```
[11:02:48] Using X-Plane
[11:02:48] Flying Challenger 650
[11:02:48] Now boarding
[11:55:58] Flaps set to 15%
```

### How do you reproduce this bug?

Fly in XP11/12 using "xplane" as the tracker/UDP
No livery detected

### Expected behavior

It needs to detect the livery. We rely on this data to approve/reject PIREPS through our automated system. At this time we have told pilots to not fly with UDP. I know this works as we have it employed on a MAC client (that isn't smartCARS 3) using UDP packets.

### Screenshots

Here is a video showing the issue. Fresh install.

https://github.com/invernyx/smartcars-3-bugs/assets/127605985/5b77c194-93a7-4c6a-8273-e29ae36fd27a

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

3.1.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

### Additional context

I need to fire up my Macbook again -- suspect if the UDP setup is the same across the board, then this problem would also manifest to Linux and Mac.

**Comment by GenericNerd** [comment] 2023-12-05 21:04
Is this only the case for UDP connections?

**Comment by walkerairtrans** [comment] 2023-12-05 21:25
> Is this only the case for UDP connections?

I am only seeing it on UDP in PC -- the MAC/Linux users have reportedly been fine.

If you use FSUIPC (with XPUIPC loaded) it doesn't happen.

**Comment by kenthieme** [comment] 2023-12-13 02:07
I can confirm this issue running on a Windows 10 Home machine via a networked connection to XPlane 12. Issue only appears to occur when using the native xplane UDP connection.

**Comment by GenericNerd** [comment] 2023-12-19 16:52
> > Is this only the case for UDP connections?
> 
> I am only seeing it on UDP in PC -- the MAC/Linux users have reportedly been fine.
> 
> If you use FSUIPC (with XPUIPC loaded) it doesn't happen.

The difference in platform is intriguing, I'll flag this up for further investigation.

**Comment by walkerairtrans** [comment] 2024-06-10 22:53
Any idea when this will get investigated? I'm still seeing this happen all the time with pilots trying to use UDP. Linux and MAC seem to be fine.

**Comment by GenericNerd** [comment] 2024-06-19 00:07
I can probably prod @Thien42 to look at this when he has time. We're obviously gearing up for Expo at the moment so I'm not sure exactly when that'll be

**Comment by Thien42** [comment] 2024-07-22 18:12
@walkerairtrans is this still an issue? I am not able to reproduce it on my end using X-Plane 12 and Windows 11.
![Screenshot 2024-07-22 201109](https://github.com/user-attachments/assets/d14449aa-b254-46ec-8d5b-6bcaf828985e)

**Comment by walkerairtrans** [comment] 2024-07-22 18:40
> @walkerairtrans is this still an issue? I am not able to reproduce it on my end using X-Plane 12 and Windows 11. ![Screenshot 2024-07-22 201109](https://private-user-images.githubusercontent.com/5628970/351068644-d14449aa-b254-46ec-8d5b-6bcaf828985e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzM4ODYsIm5iZiI6MTcyMTY3MzU4NiwicGF0aCI6Ii81NjI4OTcwLzM1MTA2ODY0NC1kMTQ0NDlhYS1iMjU0LTQ2ZWMtOGQ1Yi02YmNhZjgyODk4NWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTgzOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTUyNDhiOGQ2NGNkNDg3ZGE5MGY1NmI3ZDY5MjM5ZGJhOWFkZTNlNGY0M2IwODJjM2E0NmUwODZjNDg3N2Y0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wfgvz0lHQwXMyRS8qawM-vz5guH3VQIsE2G4fEb3s48)

I'll be home in few hours, let me check.

**Comment by walkerairtrans** [comment] 2024-07-22 21:09
> @walkerairtrans is this still an issue? I am not able to reproduce it on my end using X-Plane 12 and Windows 11. ![Screenshot 2024-07-22 201109](https://private-user-images.githubusercontent.com/5628970/351068644-d14449aa-b254-46ec-8d5b-6bcaf828985e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODI4NjAsIm5iZiI6MTcyMTY4MjU2MCwicGF0aCI6Ii81NjI4OTcwLzM1MTA2ODY0NC1kMTQ0NDlhYS1iMjU0LTQ2ZWMtOGQ1Yi02YmNhZjgyODk4NWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMjEwOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkyNDU5NjE0YzM3NDdiYzYxYjhkNTE1MThkMTg5MDRkZjA5ZmM2MTZlOGM4ZDQ0MzRkZmU0MzZjMDc0YTU4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GdbPvnEOYfhrZ9GJ3dyyVBSdaar3pn4Ipjfq5l-u8N4)

Give me couple hours; got pilots testing it back to back. Initial test for me showed it appears to be working. Just want to get few others validating too.

**Comment by walkerairtrans** [comment] 2024-07-23 13:31
@Thien42 I've had 2 people test and tell me that SC3 is disappearing/crashing on them. It's happened twice to 1 and once to another. I'll keep an eye out; but at least the livery isn't disappearing in the log. Just haven't got a successful flight from them. Looks like 2-3 hour flights in possibly the FF777. I asked them to try other planes.

**Comment by Thien42** [comment] 2024-07-23 15:29
Going to close the issue for now. 

For crashes, the users affected can write a comment on this thread: https://github.com/invernyx/smartcars-3-bugs/issues/386 or open a new one if necessary

**Closed as completed by Thien42** 2024-07-23 15:29 UTC
Labels: bug, ux, plugin, medium
