### ISSUE TITLE
[BUG] - Taxiing to Gate Quick?

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#164] opened 2023-05-03 16:00 UTC
### Describe the bug

It seems fast when transitioning from landing to taxiing to gate over SC2.

_My log is formatted..._
[15:36:07] Touched down at -152 fpm, gear lever: down, pitch: 1, roll: 2 degrees left, 141 kts
[15:36:46] Landed in 5282 ft, fuel: 5675 lb, weight: 133206 lb
[15:36:46] Taxiing to gate

This was earlier in the alpha but same quick transition.
2023-04-06T21:35:13.253Z - Flight phase set to landed
2023-04-06T21:35:38.471Z - Flaps set to 19%
2023-04-06T21:36:51.109Z - Flight phase set to taxi to_gate

### How do you reproduce this bug?

1. Land and monitor the log. It moves quickly between landed and taxiing to gate.

### Expected behavior

Maybe a bit more time? Not sure what triggers the phase. Maybe be pointless but figure I raise it up.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment] 2023-05-05 18:54
This is actually the intended behavior, albeit maybe not as clear as it should be. The "Landed in ..." log item is _not_ a flight phase - it's just a summary of landing data. It's recorded RIGHT before the taxi to gate phase as that's the point it considers the landing "over" and safe to report the information.

The "touched down" log is literally just that; the log of the touchdown. This log will be repeated for significant bounces, etc., but the "landed in..." one will not.

**Closed as not planned by turbofandude** 2023-05-05 18:54 UTC
Labels: wontfix
