### ISSUE TITLE
[BUG] - Log shows "Fuel Increased" during flight randomly

### ISSUE THREAD

**Issue by Viralwhite** [invernyx/smartcars-3-bugs#120] opened 2023-04-20 23:45 UTC
**Describe the bug**
While completing a flight today, I discovered three times the log showed "Fuel increased to xxxxx". At no point during the flight did I add any fuel and this is a concern due to the restrictions we have in our VA. This was using MSFS.

**To Reproduce**
Create a flight and watch the log. I've been unable to reproduce the error through any specific tasks during the flight. Was using the PMDG 737-7 (BCF). Didn't adjust the fuel during the flight other than the initial change when I first created the flight.

**Expected behavior**
The only point of the flight I should see fuel increased is when I specifically go into the FMC and make an adjustment.

**Screenshots**
![image](https://user-images.githubusercontent.com/87394476/233509548-bad605be-4b85-462b-a836-1d29a9448170.png)
![image](https://user-images.githubusercontent.com/87394476/233509634-d4aaffe7-7506-47ad-8e19-52447f23b8c2.png)

**System Information (please complete the following information):**
 - OS: W10 19045
 - Version: Latest
 - Plugins used: Flight Tracking, Flight Center

**Comment by GenericNerd** [comment] 2023-04-20 23:47
No information has been provided. Please edit your issue or I’ll have to close your issue as invalid

**Comment by Viralwhite** [comment] 2023-04-20 23:48
Working on that now - hit enter by mistake

**Comment by BossOfGames** [comment] 2023-04-21 00:53
Might be useful to call out which simulator this is. MSFS and P3D might handle the fuel systems differently, and FSUIPC might not be relaying the value correctly.

**Comment by Viralwhite** [comment] 2023-04-21 00:58
> NGXU (P3D) and NG3 (MSFS) might handle the fuel systems differently, and FSUIPC might not be relaying the value correctly. What sim are you running?

Appreciate the follow up and yeah, I should’ve included that. It’s MSFS.

**Comment by walkerairtrans** [comment] 2023-04-21 01:43
Looks like this is still happening.

https://github.com/invernyx/smartcars-3-bugs/issues/86

**Comment by joezat15** [comment] 2023-04-21 17:38
I have encountered the same problem. Also MSFS PMDG 737-900ER

**Comment by HondaJet** [comment] 2023-04-24 23:38
I encountered a fuel issue today also but mine is a little different.  I was flying MSFS2020 Fenix A320 with a fuel load of 24000 pounds but SC3 showed a much lower amount, something like 9800 pounds.  My pirep did not file with our VA so I can't get the exact number.
Please let me know if you would prefer this to be a new bug report.
Jerry

**Comment by turbofandude** [comment] 2023-04-26 22:09
Jerry, I'm not sure, but that sounds like a different issue (fuel accuracy). This issue will be closed as we have removed this check, in liue of simply recording the starting fuel value.

**Comment by tommaGT** [comment] 2023-04-28 19:51
Also had same issue as OP: Message in PIREP read: "2023-04-28T17:13:09.940Z - Fuel increased to 10416" after engine start and while taxiing, when no fuel was added. This was in PMDG 737-700 in MSFS. VA - Fly Virtual. Smartcars 3 Ver: 0.8.1.2.

**Comment by jordanhavard** [comment] 2023-04-29 00:10
Also still happening in QVirtual too @turbofandude

**Comment by walkerairtrans** [comment] 2023-04-29 12:05
Could be related to this still being in the flight tracker settings.

`{
      "condition": "{fuelTotalQuantityWeight} increased",
      "message": "Fuel increased to {fuelTotalQuantityWeight}",
      "timeout": 1000
    },`

I would remove that and check.

_TFDi should not be erasing this configuration on updates as it would inadvertently remove VA's custom configuration._

**Comment by jordanhavard** [comment] 2023-04-29 13:45
> I would remove that and check.

Potentially a `>` instead of a `<` somewhere around the `increased` check though and probably best to fix the root cause rather than just remove the problem

**Comment by HondaJet** [comment] 2023-05-01 20:34
I can confirm this is still happening as of today with MSFS2020 PMDG B736 on my flight it occurred 8 times, each time the fuel quantity showed a reduction.
Here is the text from this pirep showing the fuel entries.
2023-05-01T14:01:30.386Z - Fuel increased to 36599
2023-05-01T14:34:24.549Z - Pushing back
2023-05-01T14:35:01.798Z - Engine 2 On
2023-05-01T14:36:20.506Z - Engine 1 On
2023-05-01T14:37:34.339Z - Flaps set to 2%
2023-05-01T14:39:49.183Z - Fuel increased to 36487
2023-05-01T14:41:28.358Z - Taxiing out
2023-05-01T14:46:08.818Z - Taking off
2023-05-01T14:46:33.170Z - Gear lever lowered
2023-05-01T14:46:34.192Z - Climbing at 164 kts, 10 degrees pitch, -1 degrees bank
2023-05-01T14:46:38.275Z - Gear lever raised
2023-05-01T15:09:36.473Z - Cruising at 27900 ft
2023-05-01T15:13:55.963Z - Fuel increased to 31819
2023-05-01T15:24:20.402Z - Fuel increased to 30935
2023-05-01T15:53:04.875Z - Fuel increased to 28532
2023-05-01T15:53:07.906Z - Fuel increased to 28530
2023-05-01T17:04:15.747Z - Fuel increased to 22603
2023-05-01T17:28:26.569Z - Fuel increased to 20590
2023-05-01T18:53:51.045Z - Fuel increased to 13689

**Comment by turbofandude** [comment] 2023-05-02 17:52
This is due, indeed, to the default configuration including this item still. We did not remove it from the config. I've attached the default config to this if anyone affected would like to update theirs to remove it.

```
{
  "events": [
    {
      "condition": "{aircraftType} changed or {aircraftType} not_equals ''",
      "message": "Flying {aircraftType}"
    },
    {
      "condition": "{engine1Firing} not_equals false",
      "message": "Engine 1 On"
    },
    {
      "condition": "{engine1Firing} equals false",
      "message": "Engine 1 Off",
      "initialValue": true
    },
    {
      "condition": "{engine2Firing} not_equals false",
      "message": "Engine 2 On"
    },
    {
      "condition": "{engine2Firing} equals false",
      "message": "Engine 2 Off",
      "initialValue": true
    },
    {
      "condition": "{engine3Firing} not_equals false",
      "message": "Engine 3 On"
    },
    {
      "condition": "{engine3Firing} equals false",
      "message": "Engine 3 Off",
      "initialValue": true
    },
    {
      "condition": "{engine4Firing} not_equals false",
      "message": "Engine 4 On"
    },
    {
      "condition": "{engine4Firing} equals false",
      "message": "Engine 4 Off",
      "initialValue": true
    },
    {
      "condition": "{flapsControl} changed",
      "message": "Flaps set to {flapsControl}%"
    },
    {
      "condition": "{gearControl} not_equals 0",
      "message": "Gear lever lowered",
      "initialValue": true
    },
    {
      "condition": "{gearControl} equals 0",
      "message": "Gear lever raised"
    },
    {
      "condition": "{pauseFlag} equals true",
      "message": "Paused"
    },
    {
      "condition": "{pauseFlag} not_equals true",
      "message": "Unpaused",
      "initialValue": true
    },
    {
      "condition": "{slewMode} equals true",
      "message": "Slew mode entered"
    },
    {
      "condition": "{slewMode} not_equals true",
      "message": "Slew mode left",
      "initialValue": true
    },
    {
      "condition": "{simulationRate} changed",
      "message": "Sim rate changed to {simulationRate}x"
    },
    {
      "condition": "{stallWarning} equals true",
      "message": "Stalling"
    },
    {
      "condition": "{stallWarning} equals true and {ias} decreased",
      "message": "Reached minimum speed of {ias} kts",
      "timeout": 5000
    },
    {
      "condition": "{stallWarning} not_equals true",
      "message": "Stall recovered",
      "initialValue": true
    },
    {
      "condition": "{overspeedWarning} equals true",
      "message": "Overspeeding"
    },
    {
      "condition": "{overspeedWarning} equals true and {ias} increased",
      "message": "Reached maximum speed of {ias} kts",
      "timeout": 5000
    },
    {
      "condition": "{overspeedWarning} not_equals true",
      "message": "No longer overspeeding",
      "initialValue": true
    },
    {
      "condition": "{altitude} less_than 10000 and {ias} greater_than 254 and {ias} increased and {slewMode} equals false",
      "message": "Reached {ias} kts below 10,000 feet",
      "timeout": 5000
    },

    {
      "condition": "{bank} greater_than 30 or {bank} less_than -30",
      "message": "Bank exceeded 30 degrees",
      "timeout": 1000
    },
    {
      "condition": "{pitch} greater_than 20",
      "message": "Pitch exceeded 20 degrees nose up",
      "timeout": 1000
    },
    {
      "condition": "{pitch} less_than -10",
      "message": "Pitch exceeded 10 degrees nose down",
      "timeout": 1000
    },

    {
      "condition": "{phase} equals 'BOARDING'",
      "message": "Now boarding"
    },
    {
      "condition": "{phase} equals 'PUSH_BACK'",
      "message": "Pushing back with {fuelTotalQuantityWeight} lbs of fuel"
    },
    {
      "condition": "{phase} equals 'TAXI'",
      "message": "Taxiing out"
    },
    {
      "condition": "{phase} equals 'TAKE_OFF'",
      "message": "Taking off"
    },
    {
      "condition": "{phase} equals 'REJECTED_TAKE_OFF'",
      "message": "Takeoff rejected"
    },
    {
      "condition": "{phase} equals 'CLIMB'",
      "message": "Climbing at {ias} kts, {pitch} degrees pitch, {bank} degrees bank"
    },
    {
      "condition": "{phase} equals 'CRUISE'",
      "message": "Cruising at {cruiseAltitude} ft"
    },
    {
      "condition": "{phase} equals 'DESCENT'",
      "message": "Descending with {milesToGo} nm to go"
    },
    {
      "condition": "{phase} equals 'APPROACH'",
      "message": "Approach started at {altitudeAgl} ft AGL with {milesToGo} nm to go"
    },
    {
      "condition": "{phase} equals 'FINAL'",
      "message": "On final at {altitudeAgl} ft with {milesToGo} nm to go at {ias} kts, {pitch} degrees pitch, {bank} degrees bank"
    },
    {
      "condition": "{phase} equals 'LANDED'",
      "message": "Touched down at {landingRate} fpm, {gForceTouchDown}g, {ias} kts, {pitch} degrees pitch, {bank} degrees bank"
    },
    {
      "condition": "{phase} equals 'GO_AROUND'",
      "message": "Going around at {altitudeAgl} ft AGL, {ias} kts, {pitch} degrees pitch, {bank} degrees bank"
    },
    {
      "condition": "{phase} equals 'TAXI_TO_GATE'",
      "message": "Taxiing to gate, landed in {landingDistance} ft"
    }
  ]
}
```

**Closed by turbofandude** 2023-05-02 17:52 UTC
Labels: bug, ux, plugin, medium, 0.8.1

**Comment by turbofandude** [comment] 2023-05-02 17:54
Additionally, @walkerairtrans PLEASE backup any customizations you've made as we will reset _all_ changes (including logos, colors, etc.) at release to ensure everything is smooth.

**Comment by walkerairtrans** [comment] 2023-05-02 17:56
> 

AHHHH. Ok!
Will do!
