### ISSUE TITLE
[BUG] - Selected Aircraft Not Used When Filing PIREP

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#344] opened 2023-09-30 19:55 UTC
### Describe the bug

When a flight is started and the pilot selects that they are flying an aircraft that is not the same as the scheduled type, the scheduled type is what gets filed and not the actual aircraft that was selected by the pilot.  This is NOT how SC2 behaves as SC2 files the aircraft selected by the pilot at the start of the flight (as well as the load that the pilot specifies).  So, for example... I am flying a flight that is scheduled in the 737-700 and I pick the 737-800 from the drop list in SC3.  In SC3 when I file the report at the end of the flight it says that I flew the 737-700.  In SC2, the report would file with the selected 737-800.

### How do you reproduce this bug?

Bid on a flight.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/496d10f2-b858-4e7d-a1bc-4137ca485b7b)

Change the scheduled aircraft (737-800 instead of the scheduled 737-700).
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/ef64aa3d-d015-456b-aa40-8b0d8d27638e)

Fly the flight.

At the end of the flight file PIREP.

PIREP shows that the 737-700 was used.

### Expected behavior

The PIREP would show the aircraft that was selected when the flight was started.  So, if the pilot changed the aircraft to a different one then it would be filed.  If the pilot does not select a different aircraft then the scheduled one would be used (as this was the original aircraft when the flight bid was created).

So, in the example above the 737-800 should have been on the PIREP since the pilot selected a different aircraft when starting the flight.

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

3.0.0

### Plugins installed

Chat 1.0.1, Flight Center 1.0.1, Flight Tracking 1.0.3, Logbook 1.1.1, Map 1.0.0, SimBrief 1.0.0

### Additional context

API 0.3.4

Similar to closed issue #310

**Comment by GenericNerd** [comment] 2023-10-03 22:30
Are you able to please update your API and the plugins used and let me know if this is still an issue?

**Comment by walkerairtrans** [comment] 2023-10-06 01:24
I feel like this could be a stale data issue similar to what we had here in beta: https://github.com/invernyx/smartcars-3-bugs/issues/271

I have a similar issue where if an updated bid is pulled when clicking on fly (that has a different aircraft ID) the app will ignore the updated payload and fly what it has in memory.

**Comment by bryan737dfw** [comment] 2023-10-06 02:10
Our VA API was updated but I have not had a chance to fly since the update was made.  Will report back after I am able to do a test flight.

**Comment by FlyUVA-CEO** [comment] 2023-10-06 02:19
I can confirm that this issue is still present with all plugins updated and using the newest API 0.3.8.  Please see screenshots below.  I didnt actually fly this flight so didnt take a screenshot of the filed PIREP, but can provide this if needed.  SC3 is sending only the scheduled aircraft data to the live map as well as putting the Scheduled aircraft as the one flown on the filed PIREPs instead of the aircraft that the pilot selects on SC3 dropdown (if aircraft selection is allowed by the VA's admin).

Scheduled Bid card:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/0c8e7214-3faa-40c4-b70b-9f28633d7564)

SC3 Bid showing Selected AIrcraft by pilot:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/25ecead3-ed3f-47f9-b2f8-97a838756816)

SC3 Logging showing actual aircraft flying/flown:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/2c42092e-6e8d-4df3-8ca2-08855a011d4f)

Live Map/tracker showing aircraft flown is the scheduled aircraft and not selected/actual aircraft:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/b4c8fac1-9d08-4138-94fe-3b36188c2b3a)

Plugin versions:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/c958ee97-3407-4afa-9d32-273e3744481c)

API Version:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/0a73b3f6-ef41-48a7-8b37-e0ad417ff7d8)

In SC2, if a pilot selects their own aircraft type from the dropdown, that aircraft type is what is sent to the live map and also shows as the aircraft types used on the filed PIREP, not the "scheduled" aircraft thats on the bid.  SC3 seems to show ONLY the scheduled aircraft and doesnt sent the correct info to the live map or place the selected aircraft on the filed PIREP, it puts the scheduled aircraft there as well, making it look as if the pilot flew the aircraft that was scheduled and not the one selected.

Thank you guys for all you do and we look forward to a fix for this as its the last bug that we know of keeping us from making SC3 our official tracking software over SC2.

**Comment by FlyUVA-CEO** [comment] 2023-10-06 02:25
We're using phpvms 5 btw

**Comment by bryan737dfw** [comment] 2023-10-07 22:47
I haven't been able to fly myself, but I see a PIREP from someone today and it is not working as expected using API 0.3.6 (the latest public release version).  They flew a 737-800 and the PIREP was showing an A321 (which was the scheduled aircraft).  I did verify with them that they did select the 737-800 in SC3.

Log:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/0a367597-4c70-49f1-adca-8c6b217fb0d2)

SC3 PIREP:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/a8434180-ae0b-42f1-bef9-2b1e0f15094e)

Schedule:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/7d685e31-cada-41c4-bf90-6ab1d1c13263)


I am hoping to finally get a flight in either later tonight or tomorrow.

**Comment by bryan737dfw** [comment] 2023-10-08 19:00
I did a flight this morning and can confirm that the behavior still exists.  The scheduled aircraft was a 737-800.  I actually flew and selected the 737-700.  The PIREP filed with the 737-800.  

Also, have no clue where SC3 gets the passenger load for the PIREP.  What was on the PIREP was not what was on the Simbrief OFP and there is no place to specify this in SC3 (but that is a separate issue for which I will submit a report).

**Comment by thhoppst** [comment] 2023-10-10 19:48
I have the same problem Api Version 0.3.6. Smartcars V3 here

**Comment by thhoppst** [comment] 2023-10-10 20:27
I checked it with Api Version 0.3.8 same issue .... :(

**Comment by walkerairtrans** [comment] 2023-10-10 20:39
@Thien42 @GenericNerd I am 98% certain this is the same issue referenced here: https://github.com/invernyx/smartcars-3-bugs/issues/344#issuecomment-1749863892

I think the primary data cache in the app (forget what it was named and since I can't see the dev console I can't screenshot it) is not updating. So when a user clicks a new plane, the ID # is not being pushed to flight tracking. Identical problem when we had the refresh bid button problem and it would never update.

**Comment by thhoppst** [comment] 2023-10-10 21:05
Problem is in the API. complete.php ->
$data = array(
    'pilotid' => $pilotID,
    'code' => $route['code'],
    'flightnum' => $route['flightnum'],
    'depicao' => $route['depicao'],
    'arricao' => $route['arricao'],       
    'route' => implode(' ', $_POST['route']),
    'aircraft' => $route['aircraft'],   **<-------- this must be change to $_POST['aircraft']**
    'flighttime' => sprintf('%01d:%02d', floor($_POST['flightTime']), round($_POST['flightTime'] * 60) % 60),
    'landingrate' => round($_POST['landingRate']),
    'submitdate' => date('Y-m-d H:i:s'),
    'fuelused' => $_POST['fuelUsed'],
    'source' => 'smartCARS 3',
    'log' => implode('*', $_POST['flightLog'])
);

I check it on my server and it will be work.

**Comment by GenericNerd** [comment] 2023-12-05 21:08
This will be fixed in the next API version and is available at https://github.com/invernyx/smartcars-3-public-api/tree/0.3.9

**Closed as completed by GenericNerd** 2023-12-05 21:08 UTC
Labels: more info needed, verification required
