### ISSUE TITLE
[BUG] - Unable to file PIREP due to missing data

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#286] opened 2023-07-02 04:32 UTC
### Describe the bug

I flew a 2.5 hour flight that started using SimBrief on the 737-800. When complete, I was unable to file the PIREP due to this error:

```
error: Error could not complete flight, error code: 400 with message: Invalid types for aircraft (expected `int` [Raw Type: `NULL`]), flightTime (expected `double` [Raw Type: `NULL`]), route (expected `array` [Raw Type: `NULL`]) {"code":400,"name":"HttpClientError","response":{"message":"Invalid types for aircraft (expected `int` [Raw Type: `NULL`]), flightTime (expected `double` [Raw Type: `NULL`]), route (expected `array` [Raw Type: `NULL`])"},"sourceUri":"https://scdc.tfdidesign.com/newSC/api/phpvms5/flights/complete","timestamp":"2023-07-02T04:28:09.540Z"}
error: Failed to call local API {"endpoint":"api/com.tfdidesign.flight-tracking/complete","error":{"code":"ERR_BAD_RESPONSE","config":{"adapter":["xhr","http"],"data":"{}","env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"maxBodyLength":-1,"maxContentLength":-1,"method":"get","params":{},"timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://localhost:7172/api/com.tfdidesign.flight-tracking/complete","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n    at http://localhost:7172/plugins/com.tfdidesign.flight-tracking/static/js/main.f095982e.js:2:244107\n    at XMLHttpRequest.d (http://localhost:7172/plugins/com.tfdidesign.flight-tracking/static/js/main.f095982e.js:2:244255)","status":500},"timestamp":"2023-07-02T04:28:09.540Z"}
```

### How do you reproduce this bug?

Start a flight with SimBrief and the 737-800
Fly it
See if it files

### Operating system

Windows 11

### Community airline

SCDC (v5 - Production)

### smartCARS Version

0.12.0

### Plugins installed

simbrief@0.10.1, flight-tracking@0.12.0, flight-center@0.10.1

### Additional context

Interestingly, the flight-tracking plugin seems to be out of date somehow, despite this being a production build.

**Comment by bgiorgio0506** [comment] 2023-07-02 06:18
@turbofandude are the scdc prod api updated ?

**Comment by bgiorgio0506** [comment] 2023-07-25 16:56
I was not able to reproduce neither fabio so I close it until some has this error again

**Closed as not planned by bgiorgio0506** 2023-07-25 16:56 UTC
Labels: bug, plugin, high
