### ISSUE TITLE
[BUG] - Altitude still reporting incorrectly

### ISSUE THREAD

**Issue by PBCool1** [invernyx/smartcars-3-bugs#151] opened 2023-04-28 04:55 UTC
### Describe the bug

Attached are 2 pic...one showing -75500 MSFS (mine from my flight this evening). The second pic is from a staff member of my VA, he's flying on XP12...shows his cruising altitude to be 364300.

This issue was previously reported and that previous report was closed. That being said...these latest events seem to be a bit more extreme and I felt compelled to report them again including the XP12 info.

![Screenshot_1](https://user-images.githubusercontent.com/49513067/235056865-dba9372f-3fdf-4bac-a430-0f77eecd3615.png)

![image](https://user-images.githubusercontent.com/49513067/235056867-1f2a1565-85ce-4e08-a6cb-7e3fc6cb10cd.png)

### How do you reproduce this bug?

Normal flight for both pics.

### Expected behavior

Correct cruise altitude be shown...of course.

### Screenshots

See above.

### Operating system

Windows 10

### Community airline

UPSVAC

### smartCARS Version

smartCARS 3

### Plugins installed

All plus Simbrief

### Additional context

I run WideClient and Sc3 on my client PC via my network. Is there something in FSUIPC that I need to turn on/off?

This issue is being reported on XP12 also.

**Comment by jordanhavard** [comment] 2023-04-28 05:42
Also happening to QVirtual. Pilot reporting cruise as `-39000` ft

**Comment by Thien42** [comment] 2023-04-28 10:04
Can confirm I had this issue as well, we will look into it

**Comment by tommaGT** [comment] 2023-04-28 19:46
Can confirm also had same issue. MSFS - PMDG 737-700 cruise was logged as -72700 ft (actual cruise was 37000 ft). Smartcars 3 ver version 0.8.1.2. Fly Virtual VA.

**Comment by bgiorgio0506** [comment] 2023-04-28 19:57
yes the issue is related to a wrongfully implemented formula should be fixed in the next beta

**Comment by turbofandude** [comment] 2023-05-03 17:19
This will be resolved in 0.8.2 - it'll use the old logic (pre-update). We've been unable to recreate the altitude discrepency internally and until we can, we cannot fix it.

**Closed as completed by turbofandude** 2023-05-03 17:19 UTC
Labels: bug, plugin, high
