### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-bugs#305] opened 2023-07-24 11:13 UTC
### Describe the bug

cant open pilot logbook in smart cars v3 
it just shows a grey blank screen this issue is with all the members of our VA 
can this be fixed?
thank you 

### How do you reproduce this bug?

Side panel 
click on pilot logbook
it remains blank 

### Expected behavior

it should show our past flights and data 

### Screenshots

![Screenshot_694](https://github.com/invernyx/smartcars-3-bugs/assets/117974892/55a359a9-e982-435c-9dee-edc9a0cc8950)

### Operating system

Windows 10 /11

### Community airline

Airlink Virtual 

### smartCARS Version

0.12.1

### Plugins installed

logbook flight tracking chat simbrief

**Comment by Thien42** [comment] 2023-07-24 16:55
Can you confirm the version of the [public API](https://github.com/invernyx/smartcars-3-public-api) you are using?

**Comment by EpicHax7** [comment] 2023-07-24 18:55
we are using public api version 0.3.4

**Comment by jordanhavard** [comment] 2023-07-25 00:19
Also getting this issue at QVirtual on macOS latest version. We're using a custom API and this was working before the update

**Comment by EpicHax7** [comment] 2023-07-25 05:36
> Also getting this issue at QVirtual on macOS latest version. We're using a custom API and this was working before the update

ooh ig then it is a issue for all of us 
lets see

**Comment by Thien42** [comment] 2023-07-25 07:00
If this issue happens to all the users in the VA, there is most likely something wrong with the API/server setup, since we aren't able to reproduce it on our side.

I would suggest investigating server logs, and if you find that the problem is due to our code, open an issue in https://github.com/invernyx/smartcars-3-public-api

**Comment by EpicHax7** [comment] 2023-07-25 07:30
> If this issue happens to all the users in the VA, there is most likely something wrong with the API/server setup, since we aren't able to reproduce it on our side.
> 
> I would suggest investigating server logs, and if you find that the problem is due to our code, open an issue in https://github.com/invernyx/smartcars-3-public-api

sure thing will get that checked out 
thank you

**Comment by Thien42** [comment] 2023-07-25 21:54
We have found the issue and it will be fixed in the next release

**Closed as completed** 2023-07-25 21:54 UTC
Labels: bug, ux, plugin, high

**Comment by EpicHax7** [comment] 2023-07-26 05:52
> We have found the issue and it will be fixed in the next release

thank you
