### ISSUE TITLE
[BUG] - Comments Not Submitted With Flight Report

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#245] opened 2023-06-04 21:17 UTC
### Describe the bug

When submitting a flight report, comments entered on the flight tracking page are not sent with the flight report.  Pilots use the comments field to note any possible anomalies encountered during the flight and any special notes/considerations for the approver to take into account.

### How do you reproduce this bug?

1. Enter comment on the flight tracking screen.
2. Click the File PIREP button.
3. Check Crew Center admin page, no comments exist for the PIREP.

![SC3-FILE-CMT](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/b80489d1-2477-48e6-a882-47561b894793)

### Expected behavior

The entered comments should be transmitted with the PIREP and viewable in the PIREPS admin page.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/fc7f2b43-5d09-4fb9-977d-6d6cd35ef2da)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.10.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map, SimBrief

**Comment by walkerairtrans** [comment] 2023-06-04 23:08
You have hit enter after you type in your comments there. Once you do, you will see the comment added to your log trail and when the PIREP is submitted it will be added to the comment and attached to the PIREP. You can have 1 or many comments.

**Comment by bryan737dfw** [comment] 2023-06-05 02:47
I'll give that a try on my next flight... probably tomorrow evening.

**Comment by GenericNerd** [comment] 2023-06-05 16:16
As @walkerairtrans said, it is a case of pressing `ENTER` after each comment. You can add multiple comments with this method. As this is user error, this is not a bug and we won't fix it :)

**Closed as not planned by GenericNerd** 2023-06-05 16:16 UTC
Labels: wontfix

**Comment by LeCoyote** [comment] 2024-05-06 19:33
Can you please at least document this behaviour? I have found no reference to it anywhere except this bug report, which can hardly be considered proper documentation. Thanks.
