### ISSUE TITLE
[BUG] - Linux client 3.2.1 will not start on three seperate clean install distros.

### ISSUE THREAD

**Issue by paulscottrobson** [invernyx/smartcars-3-bugs#384] opened 2024-07-12 07:33 UTC
### Describe the bug

Trying to run the executable smartCars 3 v 3.2.1 Geforce RTX4060, current Nvidia drivers as appropriate.

Tried three distros ; Arch, Solus and Ubuntu 24.04 LTS. All required disabling the sandbox, and the gpu to work. Most required LIB_VA_DRIVER=nvidia to be set . (Personally I'd add Electron to the notifiable diseases list)

Problem stems from there. vainfo (video acceleration) worked okay,. Your app does not. It starts up, tries to start some sort of server, and then tries to access *something* from it which returns as a "ERR_BAD_REQUEST". and a 404 code on your own created server.

The behaviour is frankly bizarre and consistent. It puts up the login window, and it will sit there indefinitely. If you try to interact with it ; move the mouse or type something, this is when this error comes up. You don't have to click on anything, just move the mouse, so presumably it's to do with picking up messages ?

The GUI elements on the screen then promptly disappear.  The popup menu is still there.

```
info: smartCARS server running on http://localhost:7172 {"source":"main","timestamp":"2024-07-12T07:20:25.832Z"}
info: Setting current plugin {"handler":"set-current-plugin","plugin":null,"source":"realTimeAPI","timestamp":"2024-07-12T07:20:26.216Z"}
error: Failed to call local API {"endpoint":"api/credentials/retrieve/tfdidesign","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{}","env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","params":{},"timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://localhost:7172/api/credentials/retrieve/tfdidesign","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at http://localhost:7172/app/static/js/main.a6b105cc.js:2:253859\n    at XMLHttpRequest.d (http://localhost:7172/app/static/js/main.a6b105cc.js:2:254007)","status":404},"timestamp":"2024-07-12T07:20:26.244Z"}
^[^Cinfo: Stopping plugins {"timestamp":"2024-07-12T07:22:27.228Z"}
info: Socket disconnected {"handler":"disconnect","socketId":"N-B6qll8qHCDkT4PAAAB","source":"realTimeAPI","timestamp":"2024-07-12T07:22:27.231Z"}

```

### How do you reproduce this bug?

Try to run the smartcars 3 executable. Move the mouse or press some keys. 

### Expected behavior

Well, it should enter the keys (it does, maybe 3 or 4) but not go blank because your internal server is stuffed.

### Operating system

Arch (current) Solus (current) Ubuntu (24.04) 

### Community airline

N/A

### smartCARS Version

3.2.1

### Plugins installed

None. Running or not running X-Plane it doesn't affect it.

### Additional context

Why is the GUI and the monitoring not seperate ?

**Comment by Thien42** [comment] 2024-07-17 00:33
Version 3.2.2 was released, can you check if the issue is still present there?

**Comment by paulscottrobson** [comment] 2024-07-17 06:15
Runs in Arch Linux (current) without any of the previous hacks. Still displays the vainfo error which is an issue with Nvidia I think but this has no effect, can log in, select VA and so on.

Is there a smartcars 3 testbed anywhere to log into to check it's actually working with X-Plane ?

**Comment by Thien42** [comment] 2024-07-17 08:43
Not too sure I understand what you're asking for. Do you want access to a development VA?

**Comment by paulscottrobson** [comment] 2024-07-17 09:18
I was going to test it further, which requires something to connect to. I'll use a VA, it's simpler, and it's likely it will either work properly or not at all :) as it seems fairly robust on what I've tried. I was a little bit worried about using someone's VA but it's not likely to cause issues.

I'll feed back any problems I have or any setup tips. 

That reminds me. On the website there is a downloads page, which has the Windows installer, but not the Linux and Mac ones, here https://tfdidesign.com/index.php/download ; it's only downloadable from here https://smartcars.tfdidesign.com/central/download I think. 

Obviously as a Linux Simmer I'm keen to encourage SmartCars 3 as it gives me more choice.

**Comment by Thien42** [comment] 2024-07-17 09:23
I'll close the issue for now, if you have further problems you can either re-open this one or open a new one.

**Closed as completed by Thien42** 2024-07-17 09:23 UTC
Labels: verification required
