### ISSUE TITLE
[BUG] - Smartcars 3 functionality change requires engine shutdown to complete flight

### ISSUE THREAD

**Issue by doctordaveerickson** [invernyx/smartcars-3-bugs#354] opened 2023-10-08 16:26 UTC
### Describe the bug

The smartcars 3 client is requiring you to shutdown the engine in order to complete the flight.  While this may be true in real world for commercial jets, in our virtual airlines, we need to do events such as Cessna Sunday, or group flight hops where we travel to a series of airports.   In Smartcars 2 and earlier it only required you to set the brakes to complete the flight.  This functionality would add quite a bit of overhead to our virtual airline the way we function.   I would request if you want to keep this functionality in the new client, at least make it a controllable option that the virtual airline can set it to only require setting the brakes and coming to a complete stop to end the flight instead of requiring to shutdown engines.

### How do you reproduce this bug?

1. Fly a flight
2. Come to a complete stop
3. Set brakes
4. Try to file Pirep.

### Expected behavior

Expect to be able to file pirep after coming to a complete stop and setting brakes as is in previous verisons.

### Operating system

N/A

### Community airline

EasternHops

### smartCARS Version

3.1.1

### Plugins installed

chat, flight center, flight tracking, logbook, map

**Comment by GenericNerd** [comment] 2023-10-09 00:18
This is a duplicate of #355. As stated, this is intentional behaviour and you're looking at a suggestion instead of a bug report. Please refile

**Closed as not planned by GenericNerd** 2023-10-09 00:18 UTC
Labels: duplicate, invalid
