### ISSUE TITLE
[BUG] -  SC3 Not reporting/sending dispatched pax load data to VA after flight is filed

### ISSUE THREAD

**Issue by FlyUVA-CEO** [invernyx/smartcars-3-bugs#256] opened 2023-06-07 16:35 UTC
### Describe the bug

It seems that SC3 is sending the remain payload in weight instead of pax load in numbers in the complete.php file. The acars data code affected seems to be on line 43 in that file  - 'load' => &_POST['remainingLoad'],...Should this be set to retrieve and post the number of pax from the dispatch release instead?  Or will there be an option in the future to specify the number of pax so SC2 and SC3 can be used in tandem (at least until SC3 is out of beta)?  Currently, the pax load number being reported as the payload in weight units and not actual number of pax is causing extremely high revenue gains in phpvms5 since its taking that payload number as the total number of pax boarded and mutiplying it by the ticket price in the database and subtracting fuel costs to get the revenue earned.  (see screenshots below)
![Logbook1](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/ba666cb8-5f78-4814-b03f-fc16191b85e0)
![financials](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/4931bd8c-b541-46dd-ac82-f39f81dedf71)

### How do you reproduce this bug?

1. Bid a flight, fly it, and submit a flight using SC3 on a phpvms 5 system and API.
2. Go to logbook and/or financials. 

### Expected behavior

It should be reporting the number of passengers here instead of the payload weight.  In SC2, there is also box to specify the number of passengers carried and that option doesnt exist in SC3.  If possible, we would like it to put the number of passengers from the dispatch automatically or we'd love the option to specify the number of passengers in SC3 as we can in SC2. Thanks guys!

### Operating system

Windows 11

### Community airline

United Virutal Airlines flyuva.org

### smartCARS Version

latest update and API is 0.3.5 on phpvms 5

### Plugins installed

chat, map, flight tracker, logbook, flight center, simbrief

**Comment by GenericNerd** [comment] 2023-06-07 18:00
I believe this is a duplicate of #228

**Closed as not planned by GenericNerd** 2023-06-07 18:00 UTC
Labels: duplicate
