### ISSUE TITLE
[BUG] - Today's flight SC3 not connecting to Mirage VA data.

### ISSUE THREAD

**Issue by HondaJet** [invernyx/smartcars-3-bugs#171] opened 2023-05-05 19:06 UTC
### Describe the bug

I believe I have the most current version of SC3 running.  While watching the flight progress everything on SC3 side looked normal except the map did not show any aircraft in the air even though there was a known pilot ahead of me at the time.  Previous days I have seen others on the map as expected.  The biggest issue is there was no connection to our VA site so I was not showing on our VA live map.    When I tried to finish the flight in SC3 it gave me the red banner and said it failed to close the flight.   However when I checked the admin section of phpVMS I found it had indeed filed the pirep.  

I will attach my log so you can see the errors and hopefully make some sense of this.
Loving the new version even in beta so hopefully the extra work from bug reporting will slow down soon.

Flight was in MSFS2020 Fenix A320.

### How do you reproduce this bug?

I have had 100% successful flights before so don't know what caused this activity today.

### Expected behavior

All flights should complete normally when flight is done without errors.

Question:  is there somewhere in SC3 that shows the version running?  I could not find anything showing that.

### Screenshots

[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11409390/combined.log)

### Operating system

Win10

### Community airline

Mirage Executive Charters

### smartCARS Version

0.8.1.2

### Plugins installed

Flight center, Flight tracking, Logbook, Map, Chat

**Comment by HondaJet** [comment] 2023-05-05 21:24
I should also mention I have been entering SC3 through my TFDi account since you posted that should be the way to get in so we see the a/c on the SC3 map.  Don't know why none of the a/c showed up for today's flight including my own.

**Comment by HondaJet** [comment] 2023-05-08 16:50
5/8/2023,    Update as of this morning with current version my flight is logging to my VA.  
You can delete this one if you want.

**Comment by bgiorgio0506** [comment] 2023-05-08 17:05
ok if this is not a bug anymore I am gonna close it

**Closed as completed by bgiorgio0506** 2023-05-08 17:05 UTC
Labels: verification required
