### ISSUE TITLE
[BUG] - Linux Client Log Not Adhering to Configuration

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#247] opened 2023-06-06 01:24 UTC
### Describe the bug

Having an issue where the log doesn’t match the formatting or configuration of our logging configuration.

There also appears to be no taking off log entry occurring with aircraft.

### How do you reproduce this bug?

1. Start a flight
2. Monitor log

### Expected behavior

Should log data identical to the windows client and our configurations in central. 

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/6adcac5c-c8c6-47e0-843f-5a0cf038bd7b)

### Operating system

Linux

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

Chat, map, flight, logbook

**Comment by Thien42** [comment] 2023-06-06 12:06
Can you give us your flight-tracking configuration?

**Comment by walkerairtrans** [comment] 2023-06-06 12:08
> Can you give us your flight-tracking configuration?

> {
>   "events": [     
> 	{
> 	  "condition": "{aircraftType} not_equals ''",
> 	  "message": "Flying {aircraftType}"
> 	},
> 	{
> 	  "condition": "{aircraftType} changed",
> 	  "message": "Aircraft changed to {aircraftType}"
> 	},
>     {
>       "condition": "{engine1Firing} not_equals false",
>       "message": "Engine 1 On"
>     },
>     {
>       "condition": "{engine1Firing} equals false",
>       "message": "Engine 1 Off",
>       "initialValue": true
>     },
>     {
>       "condition": "{engine2Firing} not_equals false and {enginesCount} greater_than 1",
>       "message": "Engine 2 On"
>     },
>     {
>       "condition": "{engine2Firing} equals false and {enginesCount} greater_than 1",
>       "message": "Engine 2 Off",
>       "initialValue": true
>     },
>     {
>       "condition": "{engine3Firing} not_equals false and {enginesCount} greater_than 2",
>       "message": "Engine 3 On"
>     },
>     {
>       "condition": "{engine3Firing} equals false and {enginesCount} greater_than 2",
>       "message": "Engine 3 Off",
>       "initialValue": true
>     },
>     {
>       "condition": "{engine4Firing} not_equals false and {enginesCount} greater_than 3",
>       "message": "Engine 4 On"
>     },
>     {
>       "condition": "{engine4Firing} equals false and {enginesCount} greater_than 3",
>       "message": "Engine 4 Off",
>       "initialValue": true
>     },
>     {
>       "condition": "{flapsControl} changed",
>       "message": "Flaps set to {flapsControl}%",
>       "timeout": 1000
>     },
>     {
>       "condition": "{gearControl} not_equals 0",
>       "message": "Gear lever lowered",
>       "initialValue": true
>     },
>     {
>       "condition": "{gearControl} equals 0",
>       "message": "Gear lever raised"
>     },
>     {
>       "condition": "{pauseFlag} equals true",
>       "message": "Paused"
>     },
>     {
>       "condition": "{pauseFlag} not_equals true",
>       "message": "Unpaused",
>       "initialValue": true
>     },
>     {
>       "condition": "{slewMode} equals true",
>       "message": "Slew mode entered"
>     },
>     {
>       "condition": "{slewMode} not_equals true",
>       "message": "Slew mode left",
>       "initialValue": true
>     },
>     {
>       "condition": "{simulationRate} changed",
>       "message": "Simulation rate set to {simulationRate}X"
>     },
>     {
>       "condition": "{stallWarning} equals true",
>       "message": "Stalling"
>     },
>     {
>       "condition": "{stallWarning} equals true and {ias} decreased",
>       "message": "Reached minimum speed of {ias} kts",
>       "timeout": 5000
>     },
>     {
>       "condition": "{stallWarning} not_equals true",
>       "message": "Stall recovered",
>       "initialValue": true
>     },
>     {
>       "condition": "{overspeedWarning} equals true",
>       "message": "Overspeeding"
>     },
>     {
>       "condition": "{overspeedWarning} equals true and {ias} increased",
>       "message": "Reached maximum speed of {ias} kts",
>       "timeout": 5000
>     },
>     {
>       "condition": "{overspeedWarning} not_equals true",
>       "message": "No longer overspeeding",
>       "initialValue": true
>     },
>     {
>       "condition": "{altitude} less_than 10000 and {ias} greater_than 254 and {ias} increased and {slewMode} equals false",
>       "message": "Reached {ias} kts below 10,000 feet",
>       "timeout": 5000
>     },
>     {
>       "condition": "{phase} equals 'BOARDING'",
>       "message": "Now boarding"
>     },
>     {
>       "condition": "{phase} equals 'PUSH_BACK'",
>       "message": "Pushing back"
>     },
>     {
>       "condition": "{phase} equals 'TAXI'",
>       "message": "Taxiing out"
>     },
>     {
>       "condition": "{phase} equals 'TAKE_OFF'",
>       "message": "Taking off with {fuelTotalQuantityWeight} {weightUnits} of fuel"
>     },
>     {
>       "condition": "{phase} equals 'REJECT_TAKE_OFF'",
>       "message": "Takeoff rejected"
>     },
>     {
>       "condition": "{phase} equals 'CLIMB'",
>       "message": "Climbing at {ias} kts, {pitch} degrees pitch, {bank} degrees bank, with {fuelTotalQuantityWeight} {weightUnits} of fuel"
>     },
>     {
>       "condition": "{phase} equals 'CRUISE'",
>       "message": "Cruising at {cruiseAltitude} {altitudeUnits}"
>     },
>     {
>       "condition": "{phase} equals 'DESCENT'",
>       "message": "Descending with {milesToGo} nm to go"
>     },
>     {
>       "condition": "{phase} equals 'APPROACH'",
>       "message": "Approach started at {altitudeAgl} {altitudeUnits} AGL with {milesToGo} nm to go"
>     },
>     {
>       "condition": "{phase} equals 'FINAL'",
>       "message": "On final at {altitudeAgl} {altitudeUnits} with {milesToGo} nm to go at {ias} kts, {pitch} degrees pitch, {bank} degrees bank"
>     },
>     {
>       "condition": "{phase} equals 'LANDED'",
>       "message": "Touched down at {landingRate} fpm, {gForceTouchDown}g, {ias} kts, true heading {heading}, {pitch} degrees pitch, {bank} degrees bank, wind {windDirection} at {windSpeed} kts, fuel remaining {fuelTotalQuantityWeight} {weightUnits}"
>     },
> 	{
>       "condition": "{phase} equals 'LANDED' and {milesToGo} greater_than 10",
>       "message": "On the ground {milesToGo} nm from the planned arrival airfield"
>     },
>     {
>       "condition": "{phase} equals 'GO_AROUND'",
>       "message": "Going around at {altitudeAgl} {altitudeUnits} AGL, {ias} kts, {pitch} degrees pitch, {bank} degrees bank, with {fuelTotalQuantityWeight} {weightUnits} of fuel"
>     },
>     {
>       "condition": "{phase} equals 'TAXI_TO_GATE'",
>       "message": "Taxiing to gate, landed in {landingDistance} {landingDistanceUnits}"
>     },
> 	{
>       "condition": "{phase} equals 'DEBOARDING'",
>       "message": "Deboarding"
>     }
>   ]
> }

**Comment by GenericNerd** [comment] 2023-06-06 17:27
I've just checked the configuration on the database and it seems like the logger configuration is correct. I'm not sure what configuration you have sent, but this is likely related to #248 which we've discovered the cause of and are working on a fix right now.

**Comment by GenericNerd** [comment] 2023-06-06 17:37
Now that #248 is resolved, can you update your logger configuration and let us know whether this is still an issue? @walkerairtrans

**Comment by walkerairtrans** [comment] 2023-06-06 17:42
> Now that #248 is resolved, can you update your logger configuration and let us know whether this is still an issue? @walkerairtrans

Confirmed this is fixed. I was able to save my changes.

**Comment by GenericNerd** [comment] 2023-06-06 17:48
> > Now that #248 is resolved, can you update your logger configuration and let us know whether this is still an issue? @walkerairtrans
> 
> Confirmed this is fixed. I was able to save my changes.

Is this issue resolved too?

**Comment by GenericNerd** [comment] 2023-06-07 20:49
I'm going to close this issue for now, as I believe your profiler configuration was out of date due to that previous issue. Do let us know if that isn't the case anymore!

**Closed as completed by GenericNerd** 2023-06-07 20:49 UTC
Labels: invalid
