### ISSUE TITLE
[BUG] - Go Around Spam when a Go Around wasn't conducted

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#179] opened 2023-05-10 14:22 UTC
### Describe the bug

On approach, started getting spammed with G/A.

`[12:32:06] On final at 3828 ft with 10 nm to go at 195 kts, -6 degrees pitch, 2 degrees bank
[12:33:24] Going around at 2477 ft AGL, 128 kts, 9 degrees pitch, -27 degrees bank, with 4155 lb of fuel
[12:33:27] On final at 2476 ft with 9 nm to go at 127 kts, 7 degrees pitch, -13 degrees bank
[12:33:33] Going around at 2451 ft AGL, 127 kts, 9 degrees pitch, 4 degrees bank, with 4154 lb of fuel
[12:33:36] On final at 2452 ft with 9 nm to go at 129 kts, 8 degrees pitch, -3 degrees bank
[12:33:40] Going around at 2448 ft AGL, 129 kts, 8 degrees pitch, -5 degrees bank, with 4153 lb of fuel
[12:33:43] Gear lever lowered
[12:33:49] On final at 2439 ft with 8 nm to go at 131 kts, 8 degrees pitch, -2 degrees bank
[12:33:58] Going around at 2432 ft AGL, 127 kts, 8 degrees pitch, 1 degrees bank, with 4149 lb of fuel
[12:33:59] Flaps set to 67%
[12:34:01] On final at 2438 ft with 8 nm to go at 125 kts, 7 degrees pitch, -0 degrees bank`

### How do you reproduce this bug?

Unsure how to replicate this. Not even sure what was done in the first place.

### Expected behavior

No spammy spam? :)

### Screenshots

[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11442887/combined.log)

[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11442888/error.log)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment] 2023-05-10 16:57
This is caused by the go-around detection altitude being too high (3000ft agl). Fixed in 0.9.

**Closed as completed by turbofandude** 2023-05-10 16:57 UTC
Labels: bug, plugin
