### ISSUE TITLE
[BUG] - Pitch exceeded 10 degrees nose down

### ISSUE THREAD

**Issue by QFA6116** [invernyx/smartcars-3-bugs#302] opened 2023-07-20 19:38 UTC
### Describe the bug

Pitch exceeded 10 degrees nose down continually being flagged whilst in climb for no reason. See attached screenshot.

### How do you reproduce this bug?

See screenshot

### Screenshots

![Screenshot 2023-07-21 053230](https://github.com/invernyx/smartcars-3-bugs/assets/140112616/22c54bcd-6f12-4555-8bc4-64dbc9e01cd5)

### Operating system

Windows 11

### Community airline

QVirtual

### smartCARS Version

0.8.0.2

### Plugins installed

chat, map, flight centre. logbook

**Comment by Thien42** [comment] 2023-07-24 08:02
@bgiorgio0506 I've had this issue happen to me as well, I think sometimes the pitch is the wrong sign

**Comment by bgiorgio0506** [comment] 2023-07-24 08:04
@Thien42 some times or all the times ?

**Comment by Thien42** [comment] 2023-07-24 08:07
@bgiorgio0506 It has happened on all of my recent flights

**Comment by bgiorgio0506** [comment] 2023-07-24 08:09
ok then Is a sistemic issue Is It the same with XPlane UDP ? @Thien42

**Comment by Thien42** [comment] 2023-07-24 08:39
I don't seem to be able to reproduce the issue in either X-Plane UDP or MSFS with FSUIPC, so maybe it does not happen all the time. But I can confirm I had this happening to me before.

**Comment by bgiorgio0506** [comment] 2023-07-24 10:06
I have it happens once  today while testing but I cannot determine the conditions under which this bug happens as I am unable to reproduce it anymore. So basically what is happening is that the logger receive a frame with the right sign and another with the wrong sign for some reason.

**Comment by bgiorgio0506** [comment] 2023-07-24 19:19
this will be fixed at the next update

**Closed as completed** 2023-07-25 16:52 UTC
Labels: bug, ux, plugin, high
