### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by HondaJet** [invernyx/smartcars-3-bugs#129] opened 2023-04-21 15:57 UTC
### Describe the bug

Yesterday I installed SC3 on my Win10 sim computer and it opened normally and all areas showed data.  This morning I was starting a flight and when I opened SC3 I got the attached Java error.  To try to solve it I checked my task manager and found 12 instances of smartcars3 in the background processes.  After deleting them all I tried SC3 again with the same Java error.  Then I removed Java and reinstalled  build 8 ver371 and restarted the computer.  When I tried SC3 again it gave me the same Java error.   I have tried using the shortcut the install created yesterday and also getting it from the Window Start menu with the same results.

My fellow pilots at Millennium Aviation have not had this problem as of this posting.

![image](https://user-images.githubusercontent.com/131472261/233677783-e7c13578-155d-4ae5-8039-ccfb22c7191a.png)

### How do you reproduce this bug?

Every time I start SC3 for Millennium Aviation today I am getting the Java error shown above.

### Expected behavior

I should not be getting the Java error using the current version of Java with no older versions on this computer.  The Java error causes SC3 to shut down so it is not usable.

### Operating system

Win10

### Community airline

Millennium Aviation

### smartCARS Version

Since I can't get SC3 to open I can't find the version but it would be whatever the version was yesterday when I got the download installer.

### Plugins installed

Only plugins are what CEO put in SC3; since I can't get it to open right now I don't remember the ones I saw in there yesterday.

**Comment by GenericNerd** [comment] 2023-04-21 17:12
Duplicate of #124. Please try the steps I provided there. If this issue persists, reply to that issue.

**Closed as not planned by GenericNerd** 2023-04-21 17:12 UTC
Labels: duplicate
