### ISSUE TITLE
[BUG] - JSR Song Names cause UI Scrolling

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#222] opened 2023-05-29 04:24 UTC
### Describe the bug

Super long song names on JSR can cause the UI to scroll.

### How do you reproduce this bug?

1. Have a DJ put up a really long song name.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/c5677233-843b-465d-8bfe-77509d6933b8)

### Operating system

N/A

### Community airline

N/A

### smartCARS Version

0.10.0

### Plugins installed

chat, map, flight-center, flight-tracker, logbook

### Additional context

Possibly related in-kind to #215

**Comment by GenericNerd** [comment] 2023-05-30 15:43
Duplicate of #215

**Closed as not planned by GenericNerd** 2023-05-30 15:43 UTC
Labels: duplicate
