### ISSUE TITLE
[BUG] - Incorrect loading reported

### ISSUE THREAD

**Issue by FartherBranch55** [invernyx/smartcars-3-bugs#313] opened 2023-08-01 00:48 UTC
### Describe the bug

Using a self created passenger flight, on reporting it shows a cargo load number instead of the passengers used. This created incorrect values in the database for revenue. 

### How do you reproduce this bug?

1. Create a passenger flight in flight center.
2. Fly it
3. Report it
4. Check admin center and you will find a cargo loading with a cargo value instead a passenger one.

### Expected behavior

After creating a flight and finishing it, is should report the correct passenger number transported and not a cargo value. In the screenshot it shows the cargo value instead of 65 passengers!
![SC3IncorrectLoading](https://github.com/invernyx/smartcars-3-bugs/assets/73376842/3883271a-a8fb-4e81-b0b5-ad97d23855ac)

### Operating system

Windows 11 22H2

### Community airline

Noble Air

### smartCARS Version

24.4.1

### Plugins installed

chat, map, track, log, simbrief

**Comment by FartherBranch55** [comment] 2023-08-01 00:51
Incorrect screenshot uploaded. Here is the correct one.
![SC3upload ](https://github.com/invernyx/smartcars-3-bugs/assets/73376842/a8316db0-9c87-4313-9f17-653379ada4e5)

**Comment by FartherBranch55** [comment] 2023-08-01 03:04
Correct loading report should be as per screenshot below. This was corrected in admin centre.
![Screenshot 2023-08-01 130301](https://github.com/invernyx/smartcars-3-bugs/assets/73376842/7d36dfde-9100-4dc1-a0fc-47c594177e04)

**Comment by GenericNerd** [comment] 2023-08-01 11:10
Duplicate of #308

**Closed as not planned by GenericNerd** 2023-08-01 11:10 UTC
Labels: wontfix
